---
title: "Kentucky Analysis"
author: "Julie Ghekas"
date: "February 3, 2016"
output: html_document
---

I will begin to replicate the Massachusetts analysis with Kentucky, using the full data.

```{r}
mort99=read.fwf('~/Downloads/mort/MORT9913.txt',width=c(2,3,4,1,1,2,4,3,4))
colnames(mort99)=c('state','county','year','racesex','hisp','age','ICD10cause','cause','deaths')
pop99=read.fwf('~/Downloads/pop9913.txt',width=c(2,3,4,1,1,rep(8,14),25,1))
colnames(pop99)=c('state','county','year','racesex','hisp','birth','l1','a14','a59','a1014','a1519','a2024','a2534','a3544','a4554','a5564','a6574','a7584','a85','name','type')
library(reshape2)
library(car)
```

I'm now going to subset the data for the years that we want--2007-2013.  2010 is the year the ACA was enacted, so in keeping with Sommers, I'll use the three years preceding it and the three years following for the analysis.

```{r}
pop13=subset(pop99,pop99$year>=2007)
pop13=subset(pop13,pop13$type==3)
pop13$a2034=pop13$a2024+pop13$a2534
```

```{r}
agemat=aggregate(cbind(a2034,a3544,a4554,a5564)~county+state,sum,data=pop13)
ages=cbind(agemat[,1:2],100*t(apply(agemat[,3:6],1,prop.table)))

racesexmat=aggregate(cbind(count=a2034+a3544+a4554+a5564)~racesex+county+state,sum,data=pop13)
racesmat=racesexmat
racesmat$race=recode(racesexmat$racesex,"1:2=1; 3:4=2; 5:8=3")
racesmat$race[racesmat$race==1]="white"
racesmat$race[racesmat$race==2]="black"
racesmat$race[racesmat$race==3]="otherrace"
races=aggregate(count~race+county+state,sum,data=racesmat)
races=dcast(data=races,state+county~race)
race=cbind(races[,1:2],100*t(apply(races[,3:5],1,prop.table)))

sexmat=racesexmat
sexmat$sex=recode(racesexmat$racesex, "1=1; 2=2; 3=1; 4=2; 5=1; 6=2; 7=1; 8=2")
sexmat$sex[sexmat$sex==1]="male"
sexmat$sex[sexmat$sex==2]='female'
sexes=aggregate(count~sex+county+state,sum,data=sexmat) 
sexes=dcast(data=sexes,state+county~sex)
sex=cbind(sexes[,1:2],100*t(apply(sexes[,3:4],1,prop.table)))

hispmat=aggregate(cbind(count=a2034+a3544+a4554+a5564)~hisp+county+state,sum,data=pop13)
hispmat$hisp=recode(hispmat$hisp, "2=1; 1=2; 9=2")
hispmat$hisp[hispmat$hisp==1]="hisp"
hispmat$hisp[hispmat$hisp==2]='nothisp'
hisps=aggregate(count~hisp+county+state,sum,data=hispmat) 
hisps=dcast(data=hisps,state+county~hisp)
hisp=cbind(hisps[,1:2],100*t(apply(hisps[,3:4],1,prop.table)))
```

```{r}
mort13=subset(mort99,mort99$year>=2007)
mort13=subset(mort13,mort13$age>=09 & mort13$age<=13)
deaths=aggregate(deaths~county+state+year,sum,data=mort13)
pop13$pops=pop13$a2024+pop13$a2534+pop13$a3544+pop13$a4554+pop13$a5564
pops=aggregate(pops~county+state+year,sum,data=pop13)
total=merge(pops,deaths,by=c('year','state','county'))
total$mrate=total$deaths/total$pops*100000
totals=dcast(data=total,state+county~year,value.var='mrate')
colnames(totals)=c('state','county','mr07','mr08','mr09','mr10','mr11','mr12','mr13')
```

```{r}
model3data=merge(ages,race,by=c('state','county'))
model3data=merge(model3data,sex,by=c('state','county'))
model3data=merge(model3data,hisp,by=c('state','county'))
model3data=merge(model3data,totals,by=c('state','county'))
model3data$treat=0
model3data$treat[model3data$state==47]=1  #setting TN as the state control [BUT CHANGE TO KY]
```

```{r}
arhf=read.asc('~/Downloads/AHRF_2014-2015/DATA/ahrf2015.asc',gz=FALSE)
```




