---
title: "Tennessee Code"
author: "Julie Ghekas"
date: "March 25, 2016"
output: html_document
---

```{r}
library(reshape2)
library(car)
library(RItools)
library(optmatch)
load('mort99.Rdata')
load('pop99.Rdata')
arf<-read.csv('~/Downloads/arfarfsixten.csv',header=T)
colnames(arf)<-c('state','county','med610','medinc10','medinc06','pov10','pov06','ins10','ins06','unemp10','unemp06')
pop13=subset(pop99,pop99$year>=2005)
pop13=subset(pop13,pop13$type==3)
pop13$a2034=pop13$a2024+pop13$a2534
agemat=aggregate(cbind(a2034,a3544,a4554,a5564)~county+state,sum,data=pop13)
ages=cbind(agemat[,1:2],100*t(apply(agemat[,3:6],1,prop.table)))

racesexmat=aggregate(cbind(count=a2034+a3544+a4554+a5564)~racesex+county+state,sum,data=pop13)
racesmat=racesexmat
racesmat$race=recode(racesexmat$racesex,"1:2=1; 3:4=2; 5:8=3")
racesmat$race[racesmat$race==1]="white"
racesmat$race[racesmat$race==2]="black"
racesmat$race[racesmat$race==3]="otherrace"
races=aggregate(count~race+county+state,sum,data=racesmat)
races=dcast(data=races,state+county~race)
race=cbind(races[,1:2],100*t(apply(races[,3:5],1,prop.table)))

sexmat=racesexmat
sexmat$sex=recode(racesexmat$racesex, "1=1; 2=2; 3=1; 4=2; 5=1; 6=2; 7=1; 8=2")
sexmat$sex[sexmat$sex==1]="male"
sexmat$sex[sexmat$sex==2]='female'
sexes=aggregate(count~sex+county+state,sum,data=sexmat) 
sexes=dcast(data=sexes,state+county~sex)
sex=cbind(sexes[,1:2],100*t(apply(sexes[,3:4],1,prop.table)))

hispmat=aggregate(cbind(count=a2034+a3544+a4554+a5564)~hisp+county+state,sum,data=pop13)
hispmat$hisp=recode(hispmat$hisp, "2=1; 1=2; 9=2")
hispmat$hisp[hispmat$hisp==1]="hisp"
hispmat$hisp[hispmat$hisp==2]='nothisp'
hisps=aggregate(count~hisp+county+state,sum,data=hispmat) 
hisps=dcast(data=hisps,state+county~hisp)
hisp=cbind(hisps[,1:2],100*t(apply(hisps[,3:4],1,prop.table)))
mort13=subset(mort99,mort99$year>=2005)
mort13=subset(mort13,mort13$age>=09 & mort13$age<=13)
deaths=aggregate(deaths~county+state+year,sum,data=mort13)
pop13$pops=pop13$a2024+pop13$a2534+pop13$a3544+pop13$a4554+pop13$a5564
pops=aggregate(pops~county+state+year,sum,data=pop13)
total=merge(pops,deaths,by=c('year','state','county'))
total$mrate=total$deaths/total$pops*100000
totals=dcast(data=total,state+county~year,value.var='mrate')
colnames(totals)=c('state','county','mr05','mr06','mr07','mr08','mr09','mr10','mr11','mr12','mr13')
totals[is.na(totals)]=0
model3data=merge(ages,race,by=c('state','county'))
model3data=merge(model3data,sex,by=c('state','county'))
model3data=merge(model3data,hisp,by=c('state','county'))
model3data=merge(model3data,totals,by=c('state','county'))
model3data=merge(model3data,arf,by=c('state','county'))
model4data=model3dat
model4data$treat=0
model4data$treat[model4data$state==47]=1
states.tncontrol=c('4','5','6','8','9','10','17','18','19','21','24','25','26','27','30','32','33','34','35','36','38','39','41','42','44','47','50','53','54')
model4data=model4data[model4data$state %in% states.tncontrol,]
model4=glm(treat~a2034+a3544+a4554+male+white+black+hisp+mr05+mr06+mr07+mr08+mr09+mr10+pov10+medinc10+unemp10+ins10,data=model4data,family=binomial(link='logit'))
boxplot(model4)
```

```{r}
ten.treat=subset(model4data,model4data$treat==1)
ten.control=model4data[which(fitted(model4)>summary(fitted(model4))[5]),]
ten.control=subset(ten.control,ten.control$treat!=1)
ten.study=rbind(ten.treat,ten.control)
xBalance(treat~a2034+a3544+a4554+a5564+black+otherrace+white+male+hisp+mr05+mr06+mr07+mr08+mr09+mr10+pov10+medinc10+unemp10+ins10, data=ten.study,report=c('all'))
```

```{r}
fm21<-fullmatch(model4,data=model4data)
stratumStructure(fm21)
xBalance(treat~a2034+a3544+a4554+a5564+black+otherrace+white+male+hisp+mr05+mr06+mr07+mr08+mr09+mr10+pov10+medinc10+unemp10+ins10+strata(fm21),data=model4data,report=c('adj.mean.diffs','std','z','chisquare.test'))
fm22<-fullmatch(model4,data=model4data,omit.fraction=3/4)
stratumStructure(fm22)
xBalance(treat~a2034+a3544+a4554+a5564+black+otherrace+white+male+hisp+mr05+mr06+mr07+mr08+mr09+mr10+pov10+medinc10+unemp10+ins10+strata(fm22),data=model4data,report=c('adj.mean.diffs','std','z','chisquare.test'))
fm23<-fullmatch(model4,data=model4data,omit.fraction=3/4,min.control=.25,max.control=12)
stratumStructure(fm23)
axBalance(treat~a2034+a3544+a4554+a5564+black+otherrace+white+male+hisp+mr05+mr06+mr07+mr08+mr09+mr10+pov10+medinc10+unemp10+ins10+strata(fm23),data=model4data,report=c('adj.mean.diffs','std','z','chisquare.test'))

```